(declare (unit rpc))
(use medea http-client)
(client-software (list (list"Wandering Hobos" 0.1 #f)))
(define (make-train-call auth-code num operators)
  (make-call auth-code "train" 
	     (list (cons 'size  num)
		   (cons 'operators operators)
		   )
	     )
  )
(define (make-myproblems-call auth-code)
  (make-call auth-code "myproblems" #f)
)
(define (make-eval-id-call auth-code id arguments) 
  (make-call auth-code "eval" (list
			       (cons 'id id)
			       (cons 'arguments arguments)))
  )
(define (make-eval-program-call auth-code program)
  (make-call auth-code "eval" (list
			       (cons 'program program)
			       (cons 'arguments arguments)))
  )
(define (make-guess-call auth-code id program)
  (make-call auth-code "guess" (list
			       (cons 'program program)
			       (cons 'id id)))
  )
(define (make-call auth-code type params)
  (with-input-from-request (make-req-url type auth-code) (json->string params) read-json)
)
(define (make-req-url method auth-code)
  (string-append "http://icfpc2013.cloudapp.net/" method "?auth=" auth-code)
)
